Traceback (most recent call last):
  File "main.py", line 11, in <module>
    appication.listen(8000)
  File "/usr/local/lib/python2.7/site-packages/tornado/web.py", line 1691, in listen
    server.listen(port, address)
  File "/usr/local/lib/python2.7/site-packages/tornado/tcpserver.py", line 125, in listen
    sockets = bind_sockets(port, address=address)
  File "/usr/local/lib/python2.7/site-packages/tornado/netutil.py", line 145, in bind_sockets
    sock.bind(sockaddr)
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
socket.error: [Errno 48] Address already in use
Traceback (most recent call last):
  File "main.py", line 12, in <module>
    tornado.ioloop.IOLoop.instance().start() 
  File "/usr/local/lib/python2.7/site-packages/tornado/ioloop.py", line 812, in start
    event_pairs = self._impl.poll(poll_timeout)
  File "/usr/local/lib/python2.7/site-packages/tornado/platform/kqueue.py", line 67, in poll
    kevents = self._kqueue.control(None, 1000, timeout)
KeyboardInterrupt
